### PR TITLE
Add support to force delete branches

### PR DESCRIPTION
**Pull request by koomar**
Ability to force delete local change branches using `git branch -D`

### CODE REVIEW

**Comment by koomar** [comment]
cc @mcqueen-nextdoor @siminm @jhesch

**Comment by pjanakiraman** [comment]
LGTM.

**Comment by siminm** [comment]
:+1:

**Comment by siminm** [comment]
Whoa crap, did not see your comments, @jhesch, until I clicked merge and then they showed up :(

Want me to revert this?

**Comment by koomar** [comment]
Thanks @siminm - will put up the man page change soon.

**Pull request merged**
